import { IArtwork } from "../Interface/IArtwork";

// Opere della gallery artistica, ordinate dalla più recente alla più datata
// (numero d'opera del catalogo decrescente). I metadati provengono dal catalogo
// dell'artista; le descrizioni italiane sono ripulite dai refusi di scansione,
// le inglesi sono traduzioni fedeli. Le immagini WebP (thumb + full) vivono in
// public/assets/artPage/gallery/. ID statici per evitare mismatch di hydration.
export const artworks: IArtwork[] = [
  {
    id: "art-0068",
    thumb: "/assets/artPage/gallery/0068-thumb.webp",
    full: "/assets/artPage/gallery/0068-full.webp",
    width: 1600,
    height: 1600,
    title: "Poli magnetici",
    technique: { italian: "Olio e smalto su tela", english: "Oil and enamel on canvas" },
    year: "2021",
    dimensions: "99,5x99,5 cm",
    description: {
      italian:
        "Come due poli magnetici, due amanti si attirano l'un l'altro, si necessitano vicendevolmente; «ogni polo si trova sempre accoppiato ad un polo opposto», così da formare una coppia magnetica, insostituibile, inseparabile. Il campo generato da questa coppia è costellato da un'infinità di sfumature, screziato dalle più svariate tonalità. L'amore, così come la vita, non ha tinte piatte, si evolve con un'esuberanza cromatica e di contrasti.",
      english:
        "Like two magnetic poles, two lovers attract one another, they need each other; «every pole is always paired with an opposite pole», forming a magnetic couple, irreplaceable, inseparable. The field generated by this pair is studded with an infinity of nuances, streaked with the most varied shades. Love, like life, has no flat tones: it evolves with an exuberance of colour and contrast.",
    },
  },
  {
    id: "art-0063",
    thumb: "/assets/artPage/gallery/0063-thumb.webp",
    full: "/assets/artPage/gallery/0063-full.webp",
    width: 945,
    height: 1260,
    title: "Allegoria stromboliana",
    technique: {
      italian: "Acquarello e china su carta",
      english: "Watercolour and India ink on paper",
    },
    year: "2020",
    dimensions: "32x24 cm (300 g/m²)",
    description: { italian: "", english: "" },
  },
  {
    id: "art-0062",
    thumb: "/assets/artPage/gallery/0062-thumb.webp",
    full: "/assets/artPage/gallery/0062-full.webp",
    width: 787,
    height: 1181,
    title: "L'ineluttabile essenza dell'essere",
    technique: { italian: "Smalto e olio su tela", english: "Enamel and oil on canvas" },
    year: "2020",
    dimensions: "120x80 cm",
    description: {
      italian:
        "Il dipinto esprime la disintegrazione dei piani d'esistenza. Basa la sua morale sul concetto che ogni essere umano ha del significato, del valore e del motivo della vita; partendo dalla locuzione «cogito ergo sum» (penso, dunque sono), la domanda intrinseca nell'opera è: sono quel che sono, o quel che penso di essere? Quesito che porta il nostro pensiero al concetto secondo cui la nostra esistenza è resa tale da ciò che pensiamo di essa. Se così fosse, nel momento in cui svanisce il nostro concetto di esistenza, svanirebbe anche l'esistenza stessa. L'opera mostra il momento in cui non ci poniamo più queste domande, in cui non sappiamo più chi siamo, dove andiamo: la nostra visione di noi stessi viene risucchiata nel nulla, così come il nostro Universo si disgrega contemporaneamente a tutte le sfaccettature del nostro Io. Tuttavia, è forse il fatto stesso di interrogarci, di trovare una visione critica nei confronti della vita, più che l'avere le risposte, che rende l'esistenza veritiera e, dunque, mutevole.",
      english:
        "The painting expresses the disintegration of the planes of existence. Its moral rests on the notion that every human being holds a meaning, a value and a reason for life; starting from the phrase «cogito ergo sum» (I think, therefore I am), the question intrinsic to the work is: am I what I am, or what I think I am? A question that leads our thought to the idea that our existence is made such by what we think of it. If that were so, the moment our concept of existence vanishes, existence itself would vanish too. The work depicts the moment in which we no longer ask ourselves these questions, in which we no longer know who we are or where we are going: our vision of ourselves is sucked into nothingness, just as our Universe disintegrates together with every facet of our self. And yet, perhaps it is the very act of questioning, of holding a critical view of life, rather than having the answers, that makes existence truthful and therefore ever-changing.",
    },
  },
  {
    id: "art-0061",
    thumb: "/assets/artPage/gallery/0061-thumb.webp",
    full: "/assets/artPage/gallery/0061-full.webp",
    width: 886,
    height: 1181,
    title: "Icaros",
    technique: { italian: "Smalto e olio su tela", english: "Enamel and oil on canvas" },
    year: "2020",
    dimensions: "80x60 cm",
    description: {
      italian:
        "Icaro, assieme al padre Dedalo, costruì per conto di Minosse l'ingegnoso e indistricabile labirinto dove all'interno fu rinchiuso il Minotauro. Imprigionati nella torre della struttura, padre e figlio si ingegnarono costruendo delle ali con le penne degli uccelli, unite ai loro corpi grazie a della cera. Spiccato il volo verso la Sicilia, Icaro, non curante delle raccomandazioni paterne, colmo di curiosità e superbia, si spinse sempre più in alto: affascinato dall'immensa luce del Sole non si fermò fino a che non fu troppo tardi. Il calore della stella sciolse la cera che legava il piumaggio, condannandolo ad una lunga e fatale caduta verso il mare aperto. Il dipinto, tramite questa analogia, vuole enfatizzare il bisogno dell'essere umano di avere piena consapevolezza delle proprie possibilità: ambizione, conoscenza e curiosità permettono di migliorare le nostre aspettative, ma al tempo stesso è necessaria l'obiettività e la prudenza per comprendere se le scelte compiute siano a nostro sfavore.",
      english:
        "Icarus, together with his father Daedalus, built for Minos the ingenious and inextricable labyrinth in which the Minotaur was imprisoned. Locked in the tower of the structure, father and son contrived wings from birds' feathers, bound to their bodies with wax. Having taken flight towards Sicily, Icarus, heedless of his father's warnings and full of curiosity and pride, climbed ever higher: enthralled by the immense light of the Sun, he did not stop until it was too late. The star's heat melted the wax that held the plumage, condemning him to a long and fatal fall into the open sea. Through this analogy the painting seeks to emphasise the human need for full awareness of one's own possibilities: ambition, knowledge and curiosity let us raise our expectations, but objectivity and prudence are just as necessary, to understand whether the choices we make work against us.",
    },
  },
  {
    id: "art-0059",
    thumb: "/assets/artPage/gallery/0059-thumb.webp",
    full: "/assets/artPage/gallery/0059-full.webp",
    width: 787,
    height: 1181,
    title: "Blue",
    technique: { italian: "Smalto e olio su tela", english: "Enamel and oil on canvas" },
    year: "2020",
    dimensions: "30x20 cm",
    description: {
      italian:
        "Ci ritroviamo a navigare in una vita che si presenta come un oceano: assecondiamo le correnti, talvolta proviamo a contrastarle; le mareggiate ci accompagnano fra alti e bassi, fra tempeste e quiete. Siamo soli in questa immensa distesa d'acqua, ma comunque ci cerchiamo, comunque ci troviamo.",
      english:
        "We find ourselves sailing through a life that appears as an ocean: we yield to the currents, at times we try to resist them; the swells carry us between highs and lows, between storms and calm. We are alone in this immense expanse of water, yet still we seek one another, still we find one another.",
    },
  },
  {
    id: "art-0058",
    thumb: "/assets/artPage/gallery/0058-thumb.webp",
    full: "/assets/artPage/gallery/0058-full.webp",
    width: 787,
    height: 1181,
    title: "Red",
    technique: { italian: "Smalto e olio su tela", english: "Enamel and oil on canvas" },
    year: "2020",
    dimensions: "30x20 cm",
    description: {
      italian:
        "Per superare i momenti bui dobbiamo uscire dalla nostra zona comfort, alla ricerca delle nostre passioni, di ciò che ci infervora; concetti a volte astratti che in fondo fanno parte di noi.",
      english:
        "To overcome the dark moments we must step out of our comfort zone, in search of our passions, of what fires us up; concepts that are sometimes abstract yet, deep down, are part of us.",
    },
  },
  {
    id: "art-0056",
    thumb: "/assets/artPage/gallery/0056-thumb.webp",
    full: "/assets/artPage/gallery/0056-full.webp",
    width: 1143,
    height: 1600,
    title: "Il teatrante",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2020",
    dimensions: "70x50 cm",
    description: {
      italian:
        "Il dipinto vuole creare una disgiunzione fra il reale e l'inconscio. Un individuo si trova su di un palco: la scena rappresenta un istante «incompreso», che può essere il culmine d'uno spettacolo o il principio, la posa dalla quale comincia tutto; ma ogni «fine» non dev'essere altro che un nuovo inizio. Il soggetto tiene in mano una maschera: in quest'istante essa può essere indossata, così come può essere tolta per mostrare la propria essenza. Dall'attore protagonista si dirama più di un'ombra portata: alcune assecondano la postura del personaggio, altre se ne scostano completamente. Il numero delle sei ombre si rifà allo spettacolo di Luigi Pirandello «Sei personaggi in cerca d'autore», che evidenzia «il passaggio dalla persona al personaggio, dall'avere forma all'essere forma». Ognuno di noi mette in scena il proprio spettacolo e indossa una maschera per essere ciò che desidera. Dunque, siamo chi siamo o chi vogliamo essere?",
      english:
        "The painting seeks to create a disjunction between the real and the unconscious. A figure stands on a stage: the scene depicts a «misunderstood» instant, which may be the climax of a performance or its beginning, the pose from which everything starts; yet every «end» should be nothing but a new beginning. The subject holds a mask: in this instant it can be worn, just as it can be removed to reveal one's essence. From the leading actor more than one cast shadow branches out: some follow the figure's posture, others break away from it entirely. The number of six shadows recalls Luigi Pirandello's play «Six Characters in Search of an Author», which highlights «the passage from person to character, from having form to being form». Each of us stages their own performance and wears a mask to be what they wish. So then, are we who we are or who we want to be?",
    },
  },
  {
    id: "art-0055",
    thumb: "/assets/artPage/gallery/0055-thumb.webp",
    full: "/assets/artPage/gallery/0055-full.webp",
    width: 768,
    height: 960,
    title: "Karma",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2019",
    dimensions: "100x80 cm",
    description: {
      italian:
        "Il dipinto si rifà ad un concetto di karma dalle basi più logico-scientifiche che religiose o filosofiche. Nella cultura tradizionale il karma dà un senso di giustizia: ad ogni azione corrisponde una reazione analoga. Il dipinto insinua invece una realtà di caos, di entropia: ogni azione fa scaturire una serie infinita di variabili causa-effetto che si intrecciano con altre azioni e, conseguentemente, tornano al soggetto «sorgente». L'opera mostra un istante, una scelta: ogni personaggio è connesso ad altri due e tutti possono essere d'aiuto a sé stessi e agli altri. Uno di questi è sospeso nel vuoto, può essere tirato giù dal dirupo, portando con sé gli altri, oppure tirato su. I personaggi sono connessi da un filo rosso, ispirato all'omonima leggenda cinese; il filo esce dal dipinto, dando un senso di continuità. Tutti facciamo parte di un singolo organismo, siamo tutti connessi.",
      english:
        "The painting draws on a notion of karma with roots more logical-scientific than religious or philosophical. In traditional culture karma conveys a sense of justice: to every action corresponds a like reaction. The painting instead suggests a reality of chaos, of entropy: every action sets off an endless series of cause-and-effect variables that interweave with other actions and, in turn, return to the «source» subject. The work shows an instant, a choice: each figure is connected to two others, and all can help themselves and one another. One of them hangs over the void: he can be dragged down from the cliff, taking the others with him, or pulled up. The figures are linked by a red thread, inspired by the Chinese legend of the same name; the thread runs out of the painting, giving a sense of continuity. We are all part of a single organism, we are all connected.",
    },
  },
  {
    id: "art-0049",
    thumb: "/assets/artPage/gallery/0049-thumb.webp",
    full: "/assets/artPage/gallery/0049-full.webp",
    width: 1050,
    height: 1575,
    title: "Luce",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2019",
    dimensions: "120x80 cm",
    description: {
      italian:
        "Il dipinto raffigura la ricerca da parte dell'uomo dei propri bisogni, della felicità, dell'amore, rappresentati da quella luce protagonista dell'opera, alla quale i personaggi si protendono come se il suo raggiungimento fosse una competizione con gli altri o con sé stessi. Si sforzano tramite movimenti innaturali fino ad arrivarvi con una sensazione di divino torpore, come se il tempo rallentasse fin quasi a fermarsi, danzando attorno a quella illuminazione senza giungere realmente ad essa. La luce, faro nell'oscurità, crea le forme e le distanze, definisce le gradazioni lasciando in ombra tutti gli umani costrutti mentali: i grattacieli che l'uomo erige per manifestare il proprio potere, la cattedrale che costruisce per avvicinarsi al cielo, luoghi di conforto che crea per non affrontare le proprie ombre.",
      english:
        "The painting portrays the human search for one's own needs, for happiness, for love, embodied by the light at the heart of the work, towards which the figures reach as though attaining it were a contest with others or with themselves. They strain through unnatural movements until they reach it with a sense of divine torpor, as if time slowed almost to a halt, dancing around that illumination without ever truly reaching it. The light, a beacon in the darkness, creates the forms and the distances, defines the gradations while leaving in shadow all the mental constructs of humankind: the skyscrapers we raise to assert our power, the cathedral we build to draw nearer to the sky, places of comfort we make so as not to face our own shadows.",
    },
  },
  {
    id: "art-0048",
    thumb: "/assets/artPage/gallery/0048-thumb.webp",
    full: "/assets/artPage/gallery/0048-full.webp",
    width: 900,
    height: 1181,
    title: "L'equilibrista",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2019",
    dimensions: "70x50 cm",
    description: {
      italian:
        "Un uomo percorre una corda tesa fra due palazzi. La sua ombra, come le sue paure, si proietta verso il basso. La scelta di attraversare la distanza in una condizione instabile si contrappone alla irrisoria distanza tra i due edifici: i problemi possono apparire più grandi rispetto alla realtà. Si può erroneamente scegliere la via più complessa per fronteggiarli, purché vengano superati.",
      english:
        "A man crosses a rope stretched between two buildings. His shadow, like his fears, is cast downwards. The choice to cross the gap in an unstable condition stands against the trifling distance between the two buildings: problems can appear larger than they really are. One may mistakenly choose the more complicated way to face them — so long as they are overcome.",
    },
  },
  {
    id: "art-0047",
    thumb: "/assets/artPage/gallery/0047-thumb.webp",
    full: "/assets/artPage/gallery/0047-full.webp",
    width: 886,
    height: 1181,
    title: "Un telo sul mondo",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2019",
    dimensions: "40x30 cm",
    description: {
      italian:
        "Il dipinto si suddivide in due sezioni distinte: la parte in alto è ben illuminata, ogni elemento è irradiato dalla luce del sole, sia pur flebile; la parte bassa vive l'oscurità, dove tutti i problemi e le angosce della vita sono ben nascosti. Il protagonista, con un gesto sussultorio, toglie il telo che copre ciò che vogliamo tenere celato, il tappeto sotto il quale nascondiamo ciò a cui non vogliamo pensare, in modo da portare alla luce tutti gli aspetti negativi, così da poterli affrontare e quindi superare.",
      english:
        "The painting is divided into two distinct sections: the upper part is well lit, every element irradiated by sunlight, however faint; the lower part dwells in darkness, where all of life's troubles and anxieties are well hidden. The protagonist, with a sudden gesture, lifts the cloth that covers what we wish to keep concealed — the rug beneath which we hide what we would rather not think about — so as to bring every negative aspect to light, and thus be able to face and overcome it.",
    },
  },
  {
    id: "art-0046",
    thumb: "/assets/artPage/gallery/0046-thumb.webp",
    full: "/assets/artPage/gallery/0046-full.webp",
    width: 844,
    height: 1181,
    title: "Il bacio",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2019",
    dimensions: "70x50 cm",
    description: {
      italian:
        "Sia pur nella notte, risplende sotto la luce il mondo di due innamorati. Il dipinto racchiude l'universo dei due amanti, isolati l'uno con l'altra dal resto del mondo: tutta l'esistenza viene risucchiata nel vortice della loro passione, tutto si riduce in quell'istante, nel bacio di un amore. Le due parti d'una sola anima si riuniscono come una mela integra.",
      english:
        "Even in the night, the world of two lovers shines beneath the light. The painting encloses the universe of the two lovers, isolated with one another from the rest of the world: all existence is drawn into the whirl of their passion, everything narrows to that instant, to the kiss of a love. The two halves of a single soul reunite like a whole apple.",
    },
  },
  {
    id: "art-0042",
    thumb: "/assets/artPage/gallery/0042-thumb.webp",
    full: "/assets/artPage/gallery/0042-full.webp",
    width: 945,
    height: 1181,
    title: "Il labirinto",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2018",
    dimensions: "100x80 cm",
    description: {
      italian:
        "In una visione distorta del proprio mondo ci si trova dinnanzi a delle scelte: un labirinto nel quale districarsi per trovare una via d'uscita. Posti ad osservare pareti insormontabili, senza alcuna possibilità di scorgere la strada adeguata, ci si rende conto che, vedendo l'ambientazione da un punto di vista esterno, essa esiste. Sebbene resti la difficoltà nel trovare un'uscita, vi è comunque la possibilità. Il dipinto vuole spronare l'osservatore a stanare questa strada, a porsi in riflessione; il soggetto anonimo, posto ad osservare l'ingresso del labirinto, è pronto ad affrontare questo viaggio. Un orizzonte caldo apre la strada ad un cielo dal forte contrasto: la luce abbagliante che si scorge dopo aver trovato la soluzione può essere rivelata solamente se si affronta la paura di imbattersi in essa.",
      english:
        "In a distorted vision of one's own world, one faces a set of choices: a labyrinth to thread through in order to find a way out. Set to observe insurmountable walls, with no chance of glimpsing the right path, one realises that, seen from an outside point of view, that path exists. Though the difficulty of finding an exit remains, the possibility is there nonetheless. The painting means to spur the viewer to flush out this path, to enter into reflection; the anonymous figure, set to observe the entrance of the labyrinth, is ready to face the journey. A warm horizon opens the way to a sky of strong contrast: the dazzling light glimpsed once the solution is found can be revealed only if one faces the fear of coming upon it.",
    },
  },
  {
    id: "art-0041",
    thumb: "/assets/artPage/gallery/0041-thumb.webp",
    full: "/assets/artPage/gallery/0041-full.webp",
    width: 787,
    height: 1102,
    title: "Memento mori",
    technique: { italian: "Olio su tela", english: "Oil on canvas" },
    year: "2018",
    dimensions: "70x50 cm",
    description: {
      italian:
        "Memento mori: «Ricordati che devi morire». Quando, nell'antica Roma, un generale rientrava in città dopo un trionfo bellico e raccoglieva gli onori della vittoria, correva il rischio di essere sopraffatto, di paragonarsi ad una divinità. Per evitarlo qualcuno gli pronunciava la frase: «Respice post te. Hominem te memento» («Guarda dietro a te. Ricordati che sei un uomo»). Il dipinto vuole dunque evidenziare la tendenza umana a progredire verso manie di grandezza. La statua bronzea d'un individuo non meglio identificato si erge al di sopra di taluni edifici; una bandiera, simbolo di conquista, si erge ancor più in alto. La tendenza sempre maggiore di innalzarsi viene evidenziata dalle varie altezze. Una fossa riprende il concetto intrinseco della locuzione da cui si prende spunto.",
      english:
        "Memento mori: «Remember that you must die». When, in ancient Rome, a general returned to the city after a victory in war and gathered the honours of triumph, he ran the risk of being overwhelmed, of likening himself to a deity. To prevent this, someone would utter the phrase: «Respice post te. Hominem te memento» («Look behind you. Remember that you are a man»). The painting therefore seeks to highlight the human tendency to advance towards delusions of grandeur. The bronze statue of an unidentified figure rises above certain buildings; a flag, a symbol of conquest, rises higher still. The ever-growing urge to rise is conveyed through the varying heights. A pit takes up the concept inherent in the phrase from which the work draws.",
    },
  },
  {
    id: "art-0029",
    thumb: "/assets/artPage/gallery/0029-thumb.webp",
    full: "/assets/artPage/gallery/0029-full.webp",
    width: 823,
    height: 1280,
    title: "Astrazione temporale",
    technique: { italian: "Olio su tavola", english: "Oil on panel" },
    year: "2018",
    dimensions: "52,5x33 cm",
    description: {
      italian:
        "Raffigura il concetto di tempo che si evolve, in maniera astratta, nella vita dell'uomo. Un fiume accompagna questa visione, riportando ai concetti di mutamento della filosofia greca. Lo stesso fiume straborda sul passato: un passato distorto ed astratto che ci accompagna fra ricordi e persone.",
      english:
        "It portrays the concept of time evolving, in an abstract manner, within the life of man. A river accompanies this vision, recalling the notions of change of Greek philosophy. That same river overflows onto the past: a distorted and abstract past that accompanies us among memories and people.",
    },
  },
  {
    id: "art-0027",
    thumb: "/assets/artPage/gallery/0027-thumb.webp",
    full: "/assets/artPage/gallery/0027-full.webp",
    width: 981,
    height: 1600,
    title: "Presa di coscienza",
    technique: { italian: "Olio su tavola", english: "Oil on panel" },
    year: "2018",
    dimensions: "48x28,5 cm",
    description: {
      italian:
        "Una visione onirica della propria natura; racconta, fra simbolismo, pragmatismo e spiritualità, il momento in cui l'uomo prende consapevolezza del proprio essere. La presenza di figure geometriche rappresenta l'aspetto razionale e scientifico dell'uomo, la loro deformazione i limiti che ognuno ha; così come la presenza di alberi, la cui stilizzazione li riduce al minimo, rappresenta la snaturalizzazione dell'elaborazione dei concetti nella mente. L'orizzonte enfatizza una sfericità che riporta alla perfezione del cerchio, e le nuvole, sviluppate con una differenziazione cromatica, il «bene e male» all'interno dell'individuo.",
      english:
        "A dreamlike vision of one's own nature; through symbolism, pragmatism and spirituality, it recounts the moment in which man becomes aware of his own being. The presence of geometric figures represents the rational, scientific side of man, their deformation the limits each of us has; just as the presence of trees, reduced to a minimum through stylisation, represents the denaturing of how concepts are elaborated in the mind. The horizon emphasises a sphericity that recalls the perfection of the circle, and the clouds, developed through chromatic differentiation, the «good and evil» within the individual.",
    },
  },
  {
    id: "art-0017",
    thumb: "/assets/artPage/gallery/0017-thumb.webp",
    full: "/assets/artPage/gallery/0017-full.webp",
    width: 770,
    height: 1600,
    title: "Oasi",
    technique: { italian: "Olio su tavola", english: "Oil on panel" },
    year: "2017",
    dimensions: "67,5x32,5 cm",
    description: {
      italian:
        "Incentra la sua retorica sulla capacità dell'uomo di trovare speranza anche nel «deserto». La raffigurazione del fiume riporta al concetto del «Pánta rheî», il tutto scorre.",
      english:
        "Its rhetoric centres on the human capacity to find hope even in the «desert». The depiction of the river recalls the concept of «Panta rhei», everything flows.",
    },
  },
];
